import { ValidationError, ValidationResult, GenerationProfile } from '../types';
import * as crypto from 'crypto';

export class ValidationEngine {
  validate(rows: any[], fields: any[], profile: GenerationProfile): ValidationResult {
    const errors: ValidationError[] = [];
    
    let meeshoPriceCol = -1;
    let returnsPriceCol = -1;
    let variationCol = -1;
    let nameCol = -1;
    let skuCol = -1;

    // Detect key columns
    fields.forEach(f => {
      const headerLower = (f.header || '').toLowerCase();
      if (headerLower === 'meesho price') meeshoPriceCol = f.colNumber;
      if (headerLower.includes('returns') || headerLower.includes('defective')) returnsPriceCol = f.colNumber;
      if (headerLower === 'variation') variationCol = f.colNumber;
      if (headerLower === 'product name') nameCol = f.colNumber;
      if (f.fieldType === 'SKU') skuCol = f.colNumber;
    });

    const rowFingerprints = new Map<string, number>();
    const seenSKUs = new Set<string>();

    rows.forEach((row, rowIndex) => {
      // 1. Required Fields & Empty/Whitespace Check
      fields.forEach(f => {
        const val = row[f.colNumber];
        const isValEmpty = val === undefined || val === null || val.toString().trim() === '';
        
        if (f.required && isValEmpty) {
          errors.push({
            row: rowIndex,
            colNumber: f.colNumber,
            field: f.header,
            message: `Required field is empty.`,
            severity: 'error'
          });
        }

        // Validate Numeric Ranges if generated by RANDOMIZE
        if (!isValEmpty && f.generationMode === 'RANDOMIZE' && f.configuration) {
           const numVal = Number(val);
           if (isNaN(numVal)) {
             errors.push({ row: rowIndex, colNumber: f.colNumber, field: f.header, message: `Expected numeric value, got '${val}'`, severity: 'error' });
           } else {
             const base = Number(f.configuration.mainValue) || 0;
             const variation = Number(f.configuration.variation) || 0;
             const min = base - variation;
             const max = base + variation;
             const isReturnsPrice = f.header.toLowerCase().includes('returns') || f.header.toLowerCase().includes('defective');
             
             if (numVal < min || numVal > max) {
                if (!isReturnsPrice && !f.configuration.unique) {
                   errors.push({ row: rowIndex, colNumber: f.colNumber, field: f.header, message: `Value ${numVal} is outside allowed range (${min} - ${max}).`, severity: 'error' });
                }
             }
             if (!f.configuration.allowDecimal && !Number.isInteger(numVal)) {
                errors.push({ row: rowIndex, colNumber: f.colNumber, field: f.header, message: `Decimals are not allowed for this field.`, severity: 'error' });
             }
           }
        }

        // Image URL Format
        if (!isValEmpty && f.fieldType === 'Image') {
           if (!val.toString().startsWith('http://') && !val.toString().startsWith('https://')) {
             errors.push({ row: rowIndex, colNumber: f.colNumber, field: f.header, message: `Invalid image URL format. Must start with http or https.`, severity: 'error' });
           }
        }

        // Value Pool Validations (assuming template values)
        if (!isValEmpty && f.generationMode === 'VALUE_POOL' && f.configuration?.pool) {
           const isTitle = f.header.toLowerCase().includes('product name') || f.header.toLowerCase() === 'title';
           const pool = f.configuration.pool.split(',').map((s: string) => s.trim().toLowerCase());
           if (!isTitle && pool.length > 0 && !pool.includes(val.toString().trim().toLowerCase())) {
             errors.push({ row: rowIndex, colNumber: f.colNumber, field: f.header, message: `Value '${val}' is not in the allowed valid template dropdown list.`, severity: 'error' });
           }
        }
      });

      // 2. Returns Price < Meesho Price
      if (meeshoPriceCol !== -1 && returnsPriceCol !== -1) {
        const mp = Number(row[meeshoPriceCol]);
        const rp = Number(row[returnsPriceCol]);
        if (!isNaN(mp) && !isNaN(rp)) {
          if (rp >= mp) {
            errors.push({
              row: rowIndex,
              colNumber: returnsPriceCol,
              field: 'Returns Price',
              message: `Returns price (${rp}) must be strictly lower than Meesho Price (${mp}).`,
              severity: 'error'
            });
          }
        }
      }

      // 3. SKU Uniqueness
      if (skuCol !== -1) {
        const skuVal = row[skuCol]?.toString().trim() || '';
        if (skuVal && seenSKUs.has(skuVal)) {
           errors.push({ row: rowIndex, colNumber: skuCol, field: 'SKU', message: `SKU '${skuVal}' is duplicated. SKUs must be unique.`, severity: 'error' });
        }
        seenSKUs.add(skuVal);
      }

      // 4. Duplicate Row Detection (Fingerprint of configured identity fields, excluding SKU)
      const hash = crypto.createHash('sha256');
      fields.forEach(f => {
        if (f.fieldType !== 'SKU') {
           hash.update(row[f.colNumber]?.toString() || '');
        }
      });
      const fingerprint = hash.digest('hex');
      
      if (rowFingerprints.has(fingerprint)) {
        errors.push({
          row: rowIndex,
          colNumber: -1, // Indicates full row issue
          field: 'Row Fingerprint',
          message: `This row is identical (except SKU) to row ${rowFingerprints.get(fingerprint)! + 1}.`,
          severity: 'error'
        });
      } else {
        rowFingerprints.set(fingerprint, rowIndex);
      }
    });

    // 5. Mode-Specific Constraints
    if (profile.mode === 'VARIATION_MODE' && nameCol !== -1 && variationCol !== -1) {
      const baseName = rows[0][nameCol];
      const seenVariations = new Set<string>();

      rows.forEach((row, rowIndex) => {
        if (row[nameCol] !== baseName) {
           errors.push({ row: rowIndex, colNumber: nameCol, field: 'Product Name', message: `Variation Mode: Product name must be identical across all rows. Expected '${baseName}'.`, severity: 'error' });
        }

        const variationVal = row[variationCol]?.toString().trim() || '';
        if (seenVariations.has(variationVal)) {
           errors.push({ row: rowIndex, colNumber: variationCol, field: 'Variation', message: `Variation Mode: Variation value '${variationVal}' is duplicated.`, severity: 'error' });
        } else {
           seenVariations.add(variationVal);
        }
      });
    }

    if (profile.mode === 'INDEPENDENT_LISTING' && nameCol !== -1) {
      const seenNames = new Set<string>();
      rows.forEach((row, rowIndex) => {
        const nameVal = row[nameCol]?.toString().trim() || '';
        if (seenNames.has(nameVal)) {
          errors.push({ row: rowIndex, colNumber: nameCol, field: 'Product Name', message: `Independent Mode: Product name must be unique per row. '${nameVal}' is duplicated.`, severity: 'error' });
        } else {
          seenNames.add(nameVal);
        }
      });
    }

    return {
      isValid: !errors.some(e => e.severity === 'error'),
      errors
    };
  }
}
